[package]
name = "bib_search"
version = "1.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
regex = "1.6.0"
sqlparser = "0.35.0"
natord = "1.0.9"